"""added relationship

Revision ID: 686474d533f2
Revises: 6ed84ce00a0b
Create Date: 2025-11-05 16:22:58.906721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686474d533f2'
down_revision = '6ed84ce00a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'goal', ['goal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('goal_id')

    # ### end Alembic commands ###
